### ISSUE TITLE
TODO plan

### ISSUE THREAD

**Issue by nitish6174** [nitish6174/cclib-web#1]
#### Database setup
- [x] Function to loop through files in directory and parse
- [x] Determine molecular formula of parsed file
- [x] Determine InChI corresponding to parsed file
- [x] Generate SVG for parsed file
- [x] Setting up molecule document schema
- [x] Setting up parsed file document schema
- [x] Finding extreme values of attributes (for filtering purpose in API)
- [ ] Determine IUPAC and common name using InChI/other info
- [ ] Find and store data/properties about molecule using PubChemPy

#### API developement
- [x] Fetch all molecular formulas (```/api/browse/molecules```)
- [x] Fetch all parsed files (```/api/browse/files```)
- [x] Fetch documents corresponding to a molecular formula (```/api/browse/<formula>```)
- [x] Get details of a particular parsed file (specified with MongoDB document id) (```/api/file/<doc_id>```)
- [ ] Search API which supports filtering by various attributes available in parsed files (```/api/search/<search_params>```)
- [ ] Support for searching by molecule's InChI/InChIKey
- [ ] Support for searching by molecule's name
- [x] Upload a log file (```/api/upload```)
- [x] Add a log file to data repository (```/api/addfile```)
- [ ] Add authentication for APIs

#### Application web front-end
- [x] Page to upload log file and view results instantly
- [x] Page to add a log file(s) to database
- [x] Browse repository by molecular formula
- [ ] Search page
- [x] Page to show details of a particular parsed file
- [x] Button to download particular file data in JSON format (just like given by /api/file/<doc_id>)

#### Testing
- [ ] Scalability of database
- [ ] Size limit of parsed file which can be inserted as a MongoDB database
- [ ] Invalid parameters/attributes to handle and detect corrupt log files
- [ ] API testing
- [ ] Non-API URLs
- [ ] Front-end testing (using Selenium)

#### Miscellaneous
- [x] Dockerize the app
- [ ] Add option to map port for flask app and MongoDB
- [ ] Deploy an instance on a public server for user testing
- [ ] Add method to find best view when generating SVG
- [ ] Develop regex-like molecular formula matcher
- [ ] Develop support for structural search

### Partially completed (from above list)
* **Generate SVG for parsed file** : Investigate the crash issue (#4)
* **Search** : Add filters corresponding to more attributes
* **Page to show details of a particular parsed file** : Identify more attributes suitable for display in tabular form rather than separately

**Comment by ghutchis** [comment]
Here are my suggestions of "priority" todo:
## Crucial
**Testing:**
- [ ] Invalid parameters/attributes to handle and detect corrupt log files
- [ ] API testing
- [ ] Scalability of database

 **Application web front-end**
- [ ] Page to add a log file(s) to database
- [ ] Search page
- [ ] Page to show details of a particular parsed file

## Important
**API developement**
- [ ] Support for searching by molecule's InChI/InChIKey
- [ ] Support for searching by molecule's name
- [ ] Upload a log file (POST API)

## Really Nice
- [ ] Determine IUPAC and common name using InChI/other info
- [ ] Add authentication for APIs
